accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('<int:id>/', views.user_page, name="user_page"),
    path('<int:id>/follow/', views.follow, name="follow"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
    # allauth로 로그인 후 돌아가는 url
    path('profile/', views.profile, name="profile"),
]

food/urls.py
from django.urls import path
from . import views

app_name = "food"

urlpatterns = [
    path('randreci/', views.randreci, name="randreci"),
    path('recoreci/', views.recoreci, name="recoreci"),
    path('test/', views.test, name="test"),
]

my_recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts import views
from food import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('food/', include('food.urls')),
    path('', views.randreci),
    # allauth 세팅(아래에 위치)
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:id>/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('hashtags/<int:id>/', views.hashtags, name="hashtags"),
    path('<int:id>/like/', views.like, name="like"),
    path('<int:id>/update/', views.update, name="update"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('<int:id>/comment/create/', views.comment_create, name="comment_create"),
    path('<int:post_id>/comment/<int:comment_id>/delete/', views.comment_delete, name="comment_delete"),
    path('search/', views.search, name="search"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings 

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.processors import ResizeToFill
from imagekit.models import ProcessedImageField


# Create your models here.
class HashTag(models.Model):
    content = models.CharField(max_length=100)

class Post(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
                # null=True, # 필드값 유효성검사할 때 빈값도 가능
                # blank=True, # 모델폼 입력할 때 빈값도 가능
                processors=[ResizeToFill(300,300)], # 비율이 안깨지게(리스트형태)
                format='JPEG',
                options={'quality':90}, # 생략해도 상관없음
                upload_to='media' # 경로
            )
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")
    created_at = models.DateTimeField(auto_now_add=True)
    hashtags = models.ManyToManyField(HashTag, related_name="taged_post")

class Comment(models.Model):
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        # fields = UserCreationForm.Meta.fields + ('',)
        # 추가시켜줄 필드 있을 경우에 작성한다.

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model() # User모델반환 (cf. settings.AUTH_USER_MODEL은 문자열반환)
            # User모델의 이름이 바뀌어도 변경하지 않아도 되서 편리하다.
        fields = ('email', 'first_name', 'last_name',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import User


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'food:randreci')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect("food:randreci")

def user_page(request, id):
    user_info = get_object_or_404(User, id=id)
    
    # 하고있는거
    # total = user_info.followings.all()
    # 당하는거
    # total2 = user_info.followers.all()
    context = {
        'user_info': user_info
    }
    return render(request, 'accounts/user_page.html', context)

def follow(request, id):
    you = get_object_or_404(User, id=id)
    me = request.user
    # 내가 나를 팔로우할 수 없도록
    if you != me:
        if you in me.followings.all():
            me.followings.remove(you)
            # you.followers.remove(me)
        else:
            me.followings.add(you)
            # you.followers.add(me)
    return redirect('accounts:user_page', id)

def delete(request, id):
    user_info = get_object_or_404(User, id=id)
    user = request.user
    # 로그인한 유저인 경우(조건이 없어도 되지만 확인차 작성)
    if user == user_info:
        user.delete()
    return redirect('posts:index')

def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            # 비밀번호 변경 후 로그인 유지
            update_session_auth_hash(request, user)
            return redirect('posts:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

# allauth로 로그인후 돌아가는 경로
def profile(request):
    user_info = request.user
    context = {
        'user_info': user_info
    }
    return render(request, 'accounts/user_page.html', context)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4%}
{% load socialaccount %}
{% block body %}

<style>
  :root {
	--white: #e9e9e9;
	--blue: #0367a6;
	--lightblue: #008997;
  }

  .btn {
	background-color: var(--blue);
	background-image: linear-gradient(90deg, var(--blue) 0%, var(--lightblue) 74%);
	border-radius: 20px;
	border: 1px solid var(--blue);
	color: var(--white);
	cursor: pointer;
	font-weight: bold;
	letter-spacing: 0.1rem;
	padding: 0.9rem 4rem;
	text-transform: uppercase;
	transition: transform 80ms ease-in;
}

</style>


<div class="container" style="width:100%; height:100;">
  <div class="card">
    <div class="card-body px-4">
      <h1 id="title" class="card-title text-center mb-5">My Chef</h1>
      <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form show_label=False  %}
        {% if request.resolver_match.url_name == "login" %}
        <input class="btn btn-primary btn-block mt-5" type="submit" value="로그인">
        {% else %}
        <input class="btn btn-primary btn-block" type="submit" value="제출하기">
        {% endif %}
      </form>
    </div>
  </div>
  <!-- 경로이름에 따라 제목 다르게 설정하는 법 -->
  <div class="card">
    {% if request.resolver_match.url_name == "login" %}
    <div class="card-body d-flex justify-content-center">
      <p class="card-text">계정이 없으신가요?</p>
      <a href="{% url 'accounts:signup' %}" class="card-link">가입하기</a>
    </div>
    {% elif request.resolver_match.url_name == "signup" %}
    <div class="card-body d-flex justify-content-center">
      <p class="card-text">계정이 있으신가요?</p>
      <a href="{% url 'accounts:login' %}" class="card-link">로그인</a>
    </div>
    {% else %}
    <div class="card-body d-flex justify-content-center">
      <a href="{% url 'accounts:password' %}" class="card-link">비밀번호 변경</a>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

accounts/templates/accounts/user_page.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% block body %}

<style>
  :root {
    font-size: 0.8rem;
  }

  *,
  *::before,
  *::after {
    box-sizing: border-box;
  }

  body {
    font-family: "Open Sans", Arial, sans-serif;
    min-height: 100vh;
    background-color: #fafafa;
    color: #262626;
    padding-bottom: 3rem;
  }

  img {
    display: block;
  }

  .container {
    max-width: 93.5rem;
    margin: 0 auto;
    padding: 0 2rem;
  }

  .btn {
    display: inline-block;
    font: inherit;
    background: none;
    border: none;
    color: inherit;
    padding: 0;
    cursor: pointer;
  }

  .btn:focus {
    outline: 0.5rem auto #4d90fe;
  }

  .visually-hidden {
    position: absolute !important;
    height: 1px;
    width: 1px;
    overflow: hidden;
    clip: rect(1px, 1px, 1px, 1px);
  }

  /* Profile Section */

  .profile {
    padding: 5rem 0;
  }

  .profile::after {
    content: "";
    display: block;
    clear: both;
  }

  .profile-image {
    float: left;
    width: calc(33.333% - 1rem);
    display: flex;
    justify-content: center;
    align-items: center;
    margin-right: 3rem;
  }

  .profile-image img {
    border-radius: 50%;
  }

  .profile-user-settings,
  .profile-stats {
    float: left;
    width: calc(66.666% - 2rem);
  }

  .profile-user-settings {
    margin-top: 1.1rem;
  }

  .profile-user-name {
    display: inline-block;
    font-size: 2.2rem;
    font-weight: 300;
  }

  .profile-edit-btn {
    font-size: 1.4rem;
    line-height: 1.8;
    border: 0.1rem solid #dbdbdb;
    border-radius: 0.3rem;
    padding: 0 2.4rem;
    margin-left: 2rem;
  }

  .profile-settings-btn {
    font-size: 2rem;
    margin-left: 1rem;
  }

  .profile-stats {
    margin-top: 2.3rem;
  }

  .profile-stats li {
    display: inline-block;
    font-size: 1.6rem;
    line-height: 1.5;
    margin-right: 4rem;
    cursor: pointer;
  }

  .profile-stats li:last-of-type {
    margin-right: 0;
  }



  .profile-real-name,
  .profile-stat-count,
  .profile-edit-btn {
    font-weight: 600;
  }

  /* Gallery Section */

  .gallery {
    display: flex;
    flex-wrap: wrap;
    margin: -1rem -1rem;
    padding-bottom: 3rem;
  }

  .gallery-item {
    position: relative;
    flex: 1 0 22rem;
    margin: 1rem;
    color: #fff;
    cursor: pointer;
  }

  .gallery-item:hover .gallery-item-info,
  .gallery-item:focus .gallery-item-info {
    display: flex;
    justify-content: center;
    align-items: center;
    position: absolute;
    top: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.3);
  }

  .gallery-item-info {
    display: none;
  }

  .gallery-item-info li {
    display: inline-block;
    font-size: 1.7rem;
    font-weight: 600;
  }

  .gallery-item-likes {
    margin-right: 2.2rem;
  }

  .gallery-item-type {
    position: absolute;
    top: 1rem;
    right: 1rem;
    font-size: 2.5rem;
    text-shadow: 0.2rem 0.2rem 0.2rem rgba(0, 0, 0, 0.1);
  }

  .fa-clone,
  .fa-comment {
    transform: rotateY(180deg);
  }

  .gallery-image {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  /* Media Query */

  @media screen and (max-width: 40rem) {
    .profile {
      display: flex;
      flex-wrap: wrap;
      padding: 4rem 0;
    }

    .profile::after {
      display: none;
    }

    .profile-image,
    .profile-user-settings,
    .profile-stats {
      float: none;
      width: auto;
    }

    .profile-image img {
      width: 7.7rem;
    }

    .profile-user-settings {
      flex-basis: calc(100% - 10.7rem);
      display: flex;
      flex-wrap: wrap;
      margin-top: 1rem;
    }

    .profile-user-name {
      font-size: 2.2rem;
    }

    .profile-edit-btn {
      order: 1;
      padding: 0;
      text-align: center;
      margin-top: 1rem;
    }

    .profile-edit-btn {
      margin-left: 0;
    }


    .profile-edit-btn,
    .profile-stats {
      flex-basis: 100%;
    }

    .profile-stats {
      order: 1;
      margin-top: 1.5rem;
    }

    .profile-stats ul {
      display: flex;
      text-align: center;
      padding: 1.2rem 0;
      border-top: 0.1rem solid #dadada;
      border-bottom: 0.1rem solid #dadada;
    }

    .profile-stats li {
      font-size: 1.4rem;
      flex: 1;
      margin: 0;
    }

    .profile-stat-count {
      display: block;
    }
  }

  @supports (display: grid) {
    .profile {
      display: grid;
      grid-template-columns: 1fr 2fr;
      grid-template-rows: repeat(3, auto);
      grid-column-gap: 3rem;
      align-items: center;
    }

    .profile-image {
      grid-row: 1 / -1;
    }

    .gallery {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(22rem, 1fr));
      grid-gap: 2rem;
    }

    .profile-image,
    .profile-user-settings,
    .profile-stats,
    .gallery-item,
    .gallery {
      width: auto;
      margin: 0;
    }

    @media (max-width: 40rem) {
      .profile {
        grid-template-columns: auto 1fr;
        grid-row-gap: 1.5rem;
      }

      .profile-image {
        grid-row: 1 / 2;
      }

      .profile-user-settings {
        display: grid;
        grid-template-columns: auto 1fr;
        grid-gap: 1rem;
      }

      .profile-edit-btn,
      .profile-stats {
        grid-column: 1 / -1;
      }

      .profile-user-settings,
      .profile-edit-btn,
      .profile-settings-btn,
      .profile-stats {
        margin: 0;
      }
    }
  }
</style>

<header>
  <div class="container">
    <div class="profile">
      <div class="profile-image">
        <!-- <img src="https://www.iconfinder.com/data/icons/ios-7-icons/50/user_male2-512.png" alt="" style="width: 10rem;"> -->
      </div>
      <div class="profile-user-settings">
        <h1 class="profile-user-name">{{user_info.username}}</h1>

        {% if user.is_authenticated and user != user_info %}
          
          {% if user in user_info.followers.all %}
            <a class="btn profile-edit-btn fa-follow" href="{% url 'accounts:follow' user_info.id %}">언팔로우</a>
          {% else %}
            <a class="btn profile-edit-btn fa-follow" href="{% url 'accounts:follow' user_info.id %}">팔로우</a>
          {% endif %}
          
  
        {% else %}
        <a class="btn profile-edit-btn" href="{% url 'accounts:update' %}">정보수정</a>
        <form action="{% url 'accounts:delete' user_info.id %}" class="d-inline" method="post">
          {% csrf_token %}
          <input class="btn profile-edit-btn" type="submit" value="회원탈퇴">
        </form>
        {% endif %}

      </div>
      <div class="profile-stats">
        <ul>
          <li><span class="profile-stat-count">{{user_info.post_set.all | length}}</span> 게시물</li>
          
          <li>
            <button type="button" class="btn btn-outline-info btn-sm" data-toggle="modal" data-target="#followerModal">
            <span class="profile-stat-count">{{user_info.followers.all | length}}</span> 
            팔로워
          </button>
          </li>

          <li>
            <button type="button" class="btn btn-outline-info btn-sm" data-toggle="modal" data-target="#followingModal">
            <span class="profile-stat-count">{{user_info.followings.count}}</span> 
            팔로잉
          </button>
          </li>

        </ul>
      </div>
    </div>    
</header>

<main>
  <div class="container">
    <div class="gallery">
      {% for post in user_info.post_set.all %}
      <a href="{% url 'posts:detail' post.id %}">
        <div class="gallery-item" tabindex="0">
          <img src="{{post.image.url}}" class="gallery-image" alt="">
          <div class="gallery-item-info">
            <ul>
              <li class="gallery-item-likes"><span class="visually-hidden">Likes:</span><i class="fas fa-heart"
                  aria-hidden="true"></i>  {{post.like_users.count}}</li>
              <li class="gallery-item-comments"><span class="visually-hidden">Comments:</span><i class="fas fa-comment"
                  aria-hidden="true"></i>  {{post.comment_set.all.count}}</li>
            </ul>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
</main>

<!-- Button trigger modal -->
<!-- Modal -->
<div class="modal fade" id="followerModal" tabindex="-1" aria-labelledby="followerModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="justify-content: center;">
        <h5 class="modal-title" id="followerModalLabel">팔로워</h5>
      </div>
      <div class="modal-body">
        <ul style="list-style:none;">
        {% for user in user_info.followers.all %}
        <li>  
          <a href="{% url 'accounts:user_page' user.id %}">
            {{user}}
          </a>
        </li>
        {% endfor %}
      </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="followingModal" tabindex="-1" aria-labelledby="followingModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="justify-content: center;">
        <h5 class="modal-title" id="followingModalLabel">팔로잉</h5>
      </div>
      <div class="modal-body">
        <ul style="list-style:none;">
          {% for user in user_info.followings.all %}
          <li>
            <a href="{% url 'accounts:user_page' user.id %}">
              {{user}}
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}