accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('<int:id>/', views.user_page, name="user_page"),
    path('<int:id>/follow/', views.follow, name="follow"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
    # allauth로 로그인 후 돌아가는 url
    path('profile/', views.profile, name="profile"),
]

food/urls.py
from django.urls import path
from . import views

app_name = "food"

urlpatterns = [
    path('randreci/', views.randreci, name="randreci"),
    path('recoreci/', views.recoreci, name="recoreci"),
    path('test/', views.test, name="test"),
]

my_recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts import views
from food import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('food/', include('food.urls')),
    path('', views.randreci),
    # allauth 세팅(아래에 위치)
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:id>/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('hashtags/<int:id>/', views.hashtags, name="hashtags"),
    path('<int:id>/like/', views.like, name="like"),
    path('<int:id>/update/', views.update, name="update"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('<int:id>/comment/create/', views.comment_create, name="comment_create"),
    path('<int:post_id>/comment/<int:comment_id>/delete/', views.comment_delete, name="comment_delete"),
    path('search/', views.search, name="search"),
]

my_recipe/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <script src="https://kit.fontawesome.com/ceef7cd6de.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Niconne&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Gothic+A1&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Gothic+A1&family=Jua&display=swap" rel="stylesheet">


</head>

<body style="font-family: 'Gothic A1', sans-serif; ">
  <ul class="nav justify-content-center" style="margin-bottom: 2%;">
    <li class="nav-item">
      <a class="nav-link" style="color: rosybrown; font-size: 2rem; font-family: 'Jua', sans-serif;" href="{% url 'food:randreci' %}">My chef</a>
    </li>
    {% if not user.is_authenticated %}
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false" style="color: rosybrown; font-size: 2rem; font-family: 'Jua', sans-serif;">
      비회원
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="{% url 'accounts:signup' %}">회원가입</a>
      <a class="dropdown-item" href="{% url 'accounts:login' %}">로그인</a>
    </div>
  </li>
  {% endif %}
  {% if user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" style="color: rosybrown; font-size: 2rem; font-family: 'Jua', sans-serif;" href="{% url 'food:recoreci' %}">요리추천</a>
  </li>
  <li class="nav-item dropdown" >
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
    aria-haspopup="true" aria-expanded="false" style="color: rosybrown; font-size: 2rem; font-family: 'Jua', sans-serif;">
    {{user.username}} 
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:user_page' user.id %}">내 정보</a>
            <a class="dropdown-item" href="{% url 'posts:create' %}">소통하기</a>
            <a class="dropdown-item" href="{% url 'posts:index' %}">둘러보기</a>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">로그아웃</a>
          </div>
        </li>
    {% endif %}
  </ul>
 
</body>

{% block body %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>