accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('<int:id>/', views.user_page, name="user_page"),
    path('<int:id>/follow/', views.follow, name="follow"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
    # allauth로 로그인 후 돌아가는 url
    path('profile/', views.profile, name="profile"),
]

food/urls.py
from django.urls import path
from . import views

app_name = "food"

urlpatterns = [
    path('randreci/', views.randreci, name="randreci"),
    path('recoreci/', views.recoreci, name="recoreci"),
    path('test/', views.test, name="test"),
]

my_recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts import views
from food import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('food/', include('food.urls')),
    path('', views.randreci),
    # allauth 세팅(아래에 위치)
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:id>/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('hashtags/<int:id>/', views.hashtags, name="hashtags"),
    path('<int:id>/like/', views.like, name="like"),
    path('<int:id>/update/', views.update, name="update"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('<int:id>/comment/create/', views.comment_create, name="comment_create"),
    path('<int:post_id>/comment/<int:comment_id>/delete/', views.comment_delete, name="comment_delete"),
    path('search/', views.search, name="search"),
]

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.processors import ResizeToFill
from imagekit.models import ProcessedImageField


# Create your models here.
class HashTag(models.Model):
    content = models.CharField(max_length=100)

class Post(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
                # null=True, # 필드값 유효성검사할 때 빈값도 가능
                # blank=True, # 모델폼 입력할 때 빈값도 가능
                processors=[ResizeToFill(300,300)], # 비율이 안깨지게(리스트형태)
                format='JPEG',
                options={'quality':90}, # 생략해도 상관없음
                upload_to='media' # 경로
            )
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")
    created_at = models.DateTimeField(auto_now_add=True)
    hashtags = models.ManyToManyField(HashTag, related_name="taged_post")

class Comment(models.Model):
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content', 'image',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm
from .models import HashTag, Post, Comment
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse # 비동기응답

# Create your views here.


def index(request):
    posts = Post.objects.all().order_by('-created_at')

    # 한페이지에 몇개를 보여줄지
    paginator = Paginator(posts, 9) 

    page = request.GET.get('page')
    posts = paginator.get_page(page)

    comment_form = CommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'posts/index.html', context)

def detail(request, id):
    post = get_object_or_404(Post, id=id)
    comment_form = CommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'posts/detail.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        # 이미지파일은 request.FILES안에 들어있다.
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            # post object (None) 상태
            post.save()
            # post object 생성된 상태 -> 해시태그 추가
            for word in post.content.split():
                if word.startswith('#'): # word[0] == '#'과 동일
                    # get_or_create() 해당객체가 있으면 가져오고 없으면 생성한다.
                    # hashtag, created = HashTag.objects.get_or_create(content=word) # (obj, True or False) 튜플 반환
                    hashtag = HashTag.objects.get_or_create(content=word)[0] # obj만 가져오겠다.
                    post.hashtags.add(hashtag)
            return redirect(request.GET.get('next') or 'posts:index')
    else:
        form = PostForm()
    context = {
        'form': form
    }
    return render(request, 'posts/form.html', context)

def hashtags(request, id):
    hashtag = get_object_or_404(HashTag, id=id)
    posts = hashtag.taged_post.all()
    # 한페이지에 몇개를 보여줄지
    paginator = Paginator(posts, 9)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    comment_form = CommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'posts/index.html', context)

@login_required
def like(request, id):
    if request.is_ajax():
        post = get_object_or_404(Post, id=id)
        user = request.user
        if user in post.like_users.all():
            post.like_users.remove(user)
            is_like = True
        else:
            post.like_users.add(user)
            is_like = False
        
        context = {
            'is_like': is_like,
            'likes_cnt': post.like_users.all().count()
        }
        return JsonResponse(context)
        # return redirect(request.GET.get('next') or 'posts:detail', id)
    else:
        return JsonResponse({'message': '잘못된 요청입니다.'})

@login_required
def update(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            post.hashtags.clear()
            for word in post.content.split():
                if word.startswith('#'):
                    hashtag = HashTag.objects.get_or_create(content=word)[0]
                    post.hashtags.add(hashtag)
            return redirect('posts:detail', id)
    else:
        form = PostForm(instance=post)
    context = {
        'form': form
    }
    return render(request, 'posts/form.html', context)

@login_required
def delete(request, id):
    
    post = get_object_or_404(Post, id=id)
    post.delete()

    return redirect('posts:index')

@login_required
def comment_create(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
    return redirect('posts:detail', id)

@login_required
def comment_delete(request, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect('posts:detail', id=post_id)

def search(request):
    keyword = request.GET.get('keyword')
    posts = Post.objects.filter(content__icontains=keyword)
    # 한페이지에 몇개를 보여줄지
    paginator = Paginator(posts, 9) 

    page = request.GET.get('page')
    posts = paginator.get_page(page)

    comment_form = CommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'posts/index.html', context)

posts/templates/posts/_post.html
<!-- 만들어놓은 make_link모듈을 불러온다. -->

{% load make_link %}
{% load bootstrap4 %}
<div class="m-2" style="border: 0px; width: 100%;">
  <button style="position: relative;" type="button" class="btn p-0" data-toggle="modal" data-target=".bd-example-modal-lg{{post.id}}">
    <img id="post"style="width: 100%;" class="img-responsive" src="{{post.image.url}}" class="card-img-top" onmouseover="this.style.opacity='0.7';" onmouseout="this.style.opacity='1'" alt="...">
    {% comment %} <h4 id="like"><i style="position: relative; top: -10rem; color:white;" class="fas fa-heart"> {{post.like_users.count}}</i></h4> {% endcomment %}
  </button>
  <!-- <p class="card-text">{{post|hashtag_link|safe}}</p> -->
  <!-- hashtag_link(post)와 동일 -->
  <!-- safe옵션: <a></a>문자를 실제링크로 바꿔준다. -->
</div>
<div class="modal fade bd-example-modal-lg{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-6">
          <div class="modal-body">
            <img src="{{post.image.url}}"id="exampleModalCenterTitle" style="width:100%;">
          </div>
        </div>
        <div class="col-md-6">
          <div class="modal-header" style="font-weight:500;">
              <p class="modal-title" id="exampleModalCenterTitle" >
                <a href="{% url 'accounts:user_page' post.user.id %}">
                  작성자: {{post.user}}
                </a>
              {% if user.is_authenticated and user != post.user %}
                <a style="text-decoration: none;" href="{% url 'accounts:follow' post.user.id %}"> • 팔로우</a>
              {% endif %}
              </p>
                  <ul class="navbar-nav">
                      <li class="nav-item dropdown">
                          <a href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" style="color: gray;">
                              <i class="fas fa-ellipsis-h"></i>
                          </a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="font-size:10pt;">
                            <a class="dropdown-item" href="{% url 'posts:detail' post.id %}">게시글 보기</a>
                        {% if user.is_authenticated %}
                            {% if user == post.user %}
                            <a class="dropdown-item" href="{% url 'posts:update' post.id %}">수정</a>
                            <a class="dropdown-item" onclick="cancle()">삭제</a>
                          </div>
                          {% endif %}
                      {% endif %}
                      </li>
                  </ul>
          </div>
          <div class="modal-body pb-0">
            <div style="height: 60px;">
              <span style="font-weight:500;"></span>{{post|hashtag_link|safe}}
              <p class="text-muted mt-1" style="font-size:10pt;">{{post.created_at|date:'y-m-d h:m:s'}}</p>
            </div>
            {% for comment in post.comment_set.all %}
              {% if request.user == comment.user or request.user == post.user %}
                <a href="{% url 'posts:comment_delete' post.id comment.id %}">
                  <button type="button" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </a>
              {% endif %}
              <p class="m-0"><span style="font-weight:500;">{{comment.user}}</span> <span>{{comment.content}}</span></p>
            {% endfor %}
            <br>
            {% if user.is_authenticated %}
              {% if user in post.like_users.all %}
                <h4><i class="fas fa-heart heart" data-id="{{post.id}}" style="color:red;"></i> &nbsp;<i class="far fa-comment" style="color:gray;"></i></h4>
              {% else %}
                <h4><i class="far fa-heart heart" data-id="{{post.id}}" style="color:red;"></i> &nbsp;<i class="far fa-comment" style="color:gray;"></i></h4>
              {% endif %}
            {% else %}
              <a href="{% url 'posts:like' post.id %}"><h4><i class="fas fa-heart heart" style="color:red;"></i></a> &nbsp;<i class="far fa-comment" style="color:gray;"></i></h4>
            {% endif %} 
            <p style="font-size:10pt;"><span id="post{{post.id}}">{{post.like_users.count}}</span>명이 좋아합니다</p>
          </div>
          <div class="modal-footer p-1"></div>
          <form action="{% url 'posts:comment_create' post.id %}" method="post">
            {% csrf_token %}
            <div class="d-flex ml-2">
              {% bootstrap_field comment_form.content show_label=False placeholder="댓글 달기..." %}
              <input class="btn mb-3 ml-2 text-primary" type="submit" value="게시">
            </div>
          </form>
        </div>
      </div>
    </div>
    
  </div>
</div>

<script>
  function cancle(){
      if(confirm('삭제하시겠습니까?')){
          window.location.href="{% url 'posts:delete' post.id %}";
      }else{
        console.log('asdf')
          // window.location.href="#";
      }
  }
</script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
  const likeBtn = document.querySelector('.fa-heart')
  likeBtn.addEventListener('click', (e)=>{
    const postId = e.target.dataset.id
    axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest' // XHR요청
    axios.defaults.xsrfCookieName = 'csrftoken' // 쿠키안의 csrftoken
    axios.defaults.xsrfHeaderName = 'X-CSRFToken' // 헤더 설정
    axios.post(`/posts/${postId}/like/`)
      .then(response=>{
          console.log(response.data)
          if (response.data.is_like) {
            e.target.classList.remove('fas')
              e.target.classList.add('far')
          }else {
            e.target.classList.remove('far')
            e.target.classList.add('fas')
          }

          const likes_cnt = document.querySelector(`#post${postId}`)
          likes_cnt.innerText = response.data.likes_cnt
      })
      .catch(error=>{
          console.log(error)
      })    
  })
</script>

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load make_link %}
{% load bootstrap4 %}
{% block body %}
    <div class="card container p-0" style="max-width: 800px;">
        <div class="row no-gutters">
            <div class="col-md-7">
                <div class="modal-body">
                    <img src="{{post.image.url}}"id="exampleModalCenterTitle" style="width:440px;">
                </div>
                </div>
                <div class="col-md-5 pr-0">
                <div class="modal-header" style="font-weight:500;">
                    <p class="modal-title" id="exampleModalCenterTitle" >{{post.user}}
                    {% if user.is_authenticated and user != post.user %}
                        <a style="text-decoration: none;" href="{% url 'accounts:follow' post.user.id %}"> • 팔로우</a>
                    {% endif %}
                    </p>
                    {% if user.is_authenticated and user == post.user %}
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" style="color: gray;">
                                    <i class="fas fa-ellipsis-h"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="font-size:10pt;">
                                    <a class="dropdown-item" href="{% url 'posts:update' post.id %}">수정</a>
                                    <a class="dropdown-item" onclick="cancle()">삭제</a>
                                </div>
                            </li>
                        </ul>
                    {% endif %}
                </div>
                <div class="modal-body pb-0">
                    <div style="height: 120px;">
                        <span style="font-weight:500;">{{post.content}} </span>{{post|hashtag_link|safe}}
                        <p class="text-muted mt-1" style="font-size:10pt;">{{post.created_at|date:'y-m-d h:m:s'}}</p>
                    </div>
                    {% for comment in post.comment_set.all %}
                    {% if request.user == comment.user %}
                        <a href="{% url 'posts:comment_delete' post.id comment.id %}">
                            <button type="button" class="close" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </a>
                    {% endif %}
                    <p class="m-0"><span style="font-weight:500;">작성자:{{comment.user}}</span> <span style="float: right; margin-right:5px;">{{comment.content}}</span></p>
                    {% endfor %}
                    <br>
                    {% if user.is_authenticated %}
                        {% if user in post.like_users.all %}
                            <h4><i class="fas fa-heart" data-id="{{post.id}}" style="color:red;"></i> &nbsp;<i class="far fa-comment" style="color:gray;"></i></h4>
                        {% else %}
                            <h4><i class="far fa-heart" data-id="{{post.id}}" style="color:red;"></i> &nbsp;<i class="far fa-comment" style="color:gray;"></i></h4>
                        {% endif %}
                    {% endif %}
                    <p style="font-size:10pt;"><span id="post{{post.id}}">{{post.like_users.count}}</span>명이 좋아합니다</p>
                </div>
                <div class="modal-footer p-1"></div>
                    <form action="{% url 'posts:comment_create' post.id %}" method="post">
                        {% csrf_token %}
                            <div class="d-flex ml-2">
                                {% bootstrap_field comment_form.content show_label=False placeholder="댓글 달기..." %}
                            <input class="btn mb-3 ml-2 text-primary"  type="submit" value="게시">
                        </div>
                    </form>
                </div>
        </div>
    </div>
<script>
    function cancle(){
        if(confirm('삭제하시겠습니까?')){
            window.location.href="{% url 'posts:delete' post.id %}";
        }else{
            window.location.href="#";
        }
    }
</script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
  const likeBtn = document.querySelector('.fa-heart')
  likeBtn.addEventListener('click', (e)=>{
    const postId = e.target.dataset.id
    axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest' // XHR요청
    axios.defaults.xsrfCookieName = 'csrftoken' // 쿠키안의 csrftoken
    axios.defaults.xsrfHeaderName = 'X-CSRFToken' // 헤더 설정
    axios.post(`/posts/${postId}/like/`)
      .then(response=>{
          console.log(response.data)
          if (response.data.is_like) {
            e.target.classList.remove('fas')
              e.target.classList.add('far')
          }else {
            e.target.classList.remove('far')
            e.target.classList.add('fas')
          }

          const likes_cnt = document.querySelector(`#post${postId}`)
          likes_cnt.innerText = response.data.likes_cnt
      })
      .catch(error=>{
          console.log(error)
      })    
  })
</script>
{% endblock %}

posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<style>
  :root {
	--white: #e9e9e9;
	--blue: #0367a6;
	--lightblue: #008997;
  }

  .btn {
	background-color: var(--blue);
	background-image: linear-gradient(90deg, var(--blue) 0%, var(--lightblue) 74%);
	border-radius: 20px;
	border: 1px solid var(--blue);
	color: var(--white);
	cursor: pointer;
	font-weight: bold;
	letter-spacing: 0.1rem;
	padding: 0.9rem 4rem;
	text-transform: uppercase;
	transition: transform 80ms ease-in;
}

</style>

  <div class="container" style="width:100%; height:100;">
      <div class="card" style="width: 50vh; margin:0 auto;">
        <div class="card-body">
          <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-primary btn-block" type="submit">새 글 작성</button>
          </form>
        </div>
      </div>
  </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% block body %}
{% load make_link %}
{% load bootstrap4 %}
<style>

.container{
  display:flex;
  flex-direction:column;
  align-items:center;
}
.left{
  width:300px;
}
.name{
  padding:16px;
  width:300px;
}
.image{
  border-top:1px solid gray;
}
.con{
  border: 1px solid gray;
}

</style>
<div class = "container">
  {% for post in posts %}
  <div class = 'con'>
    <div class = 'name'> 
    작성자: {{post.user}}
    </div>
    <div class = 'image'>
      {% include 'posts/_post.html' %}
    </div>
    <div class = 'left'>
    <div class="modal-body">
      <div>
        <p class="text-muted mt-1" style="font-size:10pt; ">{{post.created_at|date:'y-m-d h:m:s'}}</p>
      </div>
    </div>
    <div class="modal-footer p-1"></div> 
    </div>
  </div>
  {% empty %}
    <p>포스트가 존재하지 않습니다.</p>
    
  {% endfor %}
    
</div>

<div class="d-flex justify-content-center">
  {% bootstrap_paginate posts %}
</div>
{% endblock %}

<script>
    function cancle(){
        if(confirm('삭제하시겠습니까?')){
            window.location.href="{% url 'posts:delete' post.id %}";
        }else{
            window.location.href="#";
        }
    }
</script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
  const likeBtn = document.querySelector('.fa-heart')
  likeBtn.addEventListener('click', (e)=>{
    const postId = e.target.dataset.id
    console.log(postId)
    axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest' // XHR요청
    axios.defaults.xsrfCookieName = 'csrftoken' // 쿠키안의 csrftoken
    axios.defaults.xsrfHeaderName = 'X-CSRFToken' // 헤더 설정
    axios.post(`/posts/${postId}/like/`)
      .then(response=>{
          console.log(response.data)
          if (response.data.is_like) {
            e.target.classList.remove('fas')
              e.target.classList.add('far')
          }else {
            e.target.classList.remove('far')
            e.target.classList.add('fas')
          }

          const likes_cnt = document.querySelector(`#post${postId}`)
          likes_cnt.innerText = response.data.likes_cnt
      })
      .catch(error=>{
          console.log(error)
      })    
  })
</script>